@startuml

title Exceptions Hierarchy

skinparam class {
BackgroundColor<<error>> tomato
BackgroundColor<<unchecked>> orange
BackgroundColor<<checked>> palegreen
}

class Throwable {
  + toString(): String
  + getMessage(): String
  + getLocalizedMessage(): String
  + getCause(): Throwable
  ~ setCause(cause: Throwable): void
  + initCause(cause: Throwable): Throwable
  + setStackTrace(s: StackTraceElement[]): void
  + getStackTrace(): StackTraceElement[]
  + printStackTrace(): void
  + fillInStackTrace(): Throwable
  + addSuppressed(Throwable exception): void
  + getSuppressed(): Throwable[]
}

class Error <<error>> extends Throwable
class ThreadDeath <<error>> extends Error
class LinkageError <<error>> extends Error
class AssertionError <<error>> extends Error
class VirtualMachineError <<error>> extends Error
class StackOverflowError <<error>> extends VirtualMachineError
class OutOfMemoryError <<error>> extends VirtualMachineError

class Exception<<checked>> extends Throwable
class IOException<<checked>> extends Exception
class InterruptedException<<checked>> extends Exception
class NamingException<<checked>> extends Exception
class ReflectiveOperationException<<checked>> extends Exception
class SQLException<<checked>> extends Exception

class RuntimeException<<unchecked>> extends Exception
class NullPointerException<<unchecked>> extends RuntimeException
class ClassCastException<<unchecked>> extends RuntimeException
class IndexOutOfBoundsException<<unchecked>> extends RuntimeException
class ArithmeticException<<unchecked>> extends RuntimeException

@enduml